# Generated by Django 2.2.1 on 2019-05-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('admin_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors_name', models.CharField(max_length=255)),
                ('authors_institute', models.CharField(max_length=255, null=True)),
                ('venue', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField(null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255, null=True)),
                ('n_citation', models.IntegerField(default=0)),
                ('references', models.CharField(max_length=65535)),
                ('doc_type', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255, null=True)),
                ('issn', models.CharField(max_length=255, null=True)),
                ('isbn', models.CharField(max_length=255, null=True)),
                ('pdf', models.URLField()),
                ('url', models.URLField()),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(db_index=True, max_length=21, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=21)),
                ('user_name', models.CharField(max_length=21)),
                ('credit', models.IntegerField(default=0)),
                ('interest', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('avator', models.ImageField(upload_to='')),
                ('signature', models.TextField(null=True)),
                ('type', models.IntegerField(choices=[(0, '普通用户'), (1, '专家')], default=0)),
                ('institute', models.CharField(max_length=255, null=True)),
                ('field', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('tendency', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('time', models.DateField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backends.Users')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backends.Papers')),
            ],
        ),
        migrations.AddField(
            model_name='papers',
            name='belonging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backends.Users'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '上传论文认证'), (2, '身份认证'), (3, '论文归属权申诉')])),
                ('content', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('object_id', models.CharField(max_length=255)),
                ('state', models.IntegerField(choices=[(0, '未处理'), (1, '肯定'), (2, '否定')])),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backends.Users')),
            ],
        ),
    ]
