import json
from django.http import HttpResponse, HttpResponseRedirect, FileResponse, JsonResponse
from django.shortcuts import render
import  random
from django.views.decorators.csrf import csrf_exempt
keyword_value = [
{"name":"智能手表","value":"1199"},
{"name":"智能","value":"1074"},
{"name":"智能手环","value":"1022"},
{"name":"自动化","value":"990"},
{"name":"应力","value":"826"},
{"name":"智能手机","value":"780"},
{"name":"长篇小说","value":"780"},
{"name":"住房贷款","value":"685"},
{"name":"自动化测试","value":"487"},
{"name":"智能化","value":"415"},
{"name":"智能交通","value":"356"},
{"name":"智能电网","value":"345"},
{"name":"振荡器","value":"252"},
{"name":"语音信箱","value":"243"},
{"name":"智能照明","value":"214"},
{"name":"智能控制","value":"211"},
{"name":"智能监控","value":"188"},
{"name":"智能卡","value":"184"},
{"name":"英特网","value":"173"},
{"name":"永磁材料","value":"169"},
{"name":"有机高分子材料","value":"168"},
{"name":"智能材料","value":"159"},
{"name":"智能材料","value":"159"},
{"name":"异步通信","value":"145"},
{"name":"智能窗","value":"143"},
{"name":"在线软件","value":"132"},
{"name":"英语导游","value":"125"},
{"name":"中学教育","value":"110"},
{"name":"人工智能","value":"4257"},
{"name":"养老保险","value":"3491"},
{"name":"期货","value":"2948"},
{"name":"内存条","value":"1648"},
{"name":"物理","value":"1503"},
{"name":"四维","value":"1238"},
{"name":"抛光","value":"820"},
{"name":"蒙古语","value":"525"},
{"name":"模具设计","value":"493"},
{"name":"物理实验","value":"485"},
{"name":"物理化学","value":"470"},
{"name":"宽带接入","value":"447"},
{"name":"新西兰留学","value":"340"},
{"name":"切片机","value":"328"},
{"name":"马来语","value":"300"},
{"name":"橡胶垫片","value":"275"},
{"name":"网络管理","value":"247"},
{"name":"模具加工","value":"245"},
{"name":"碳纤维复合材料","value":"233"},
{"name":"陶瓷材料","value":"220"},
{"name":"科教","value":"216"},
{"name":"叶片泵","value":"211"},
{"name":"生物材料","value":"195"},
{"name":"绝热材料","value":"166"},
{"name":"密封材料","value":"152"},
{"name":"纳米复合材料","value":"140"},
{"name":"生态环境材料","value":"44"},
{"name":"卷染机","value":"42"},
{"name":"计算机","value":"8889"},
{"name":"黄金","value":"4969"},
{"name":"基金","value":"3088"},
{"name":"计算机科学与技术","value":"1421"},
{"name":"计算机专业","value":"1050"},
{"name":"国际商务","value":"536"},
{"name":"计算机应用","value":"492"},
{"name":"计算机语言","value":"483"},
{"name":"机械臂","value":"454"},
{"name":"计算机基础","value":"385"},
{"name":"计算机科学与技术专业","value":"382"},
{"name":"计算机仿真","value":"373"},
{"name":"呼叫中心","value":"372"},
{"name":"监控器","value":"360"},
{"name":"金属材料","value":"334"},
{"name":"机械效率","value":"308"},
{"name":"计算机辅助设计","value":"306"},
{"name":"计算机软件","value":"297"},
{"name":"聚氨酯泡沫","value":"243"},
{"name":"国际长途","value":"215"},
{"name":"计算机导论","value":"167"},
{"name":"机械模型","value":"164"},
{"name":"金融软件","value":"150"},
{"name":"计算机控制","value":"132"},
{"name":"计算机维护","value":"123"},
{"name":"股市动态","value":"112"},
{"name":"函授学校","value":"107"},
{"name":"计算机软件技术基础","value":"69"},
{"name":"金融机具","value":"60"},
{"name":"复合材料","value":"859"},
{"name":"材料科学与工程","value":"672"},
{"name":"高分子材料","value":"605"},
{"name":"法医学","value":"490"},
{"name":"大学物理","value":"449"},
{"name":"大学物理","value":"449"},
{"name":"财务公司","value":"378"},
{"name":"大学计算机基础","value":"288"},
{"name":"功能材料","value":"276"},
{"name":"保险理赔","value":"267"},
{"name":"储蓄银行","value":"266"},
{"name":"保险咨询","value":"244"},
{"name":"动画下载","value":"237"},
{"name":"保险代理","value":"229"},
{"name":"股票投资","value":"227"},
{"name":"电脑知识","value":"217"},
{"name":"工程设备","value":"195"},
{"name":"供暖设备","value":"189"},
{"name":"股票数据","value":"185"},
{"name":"表演艺术","value":"185"},
{"name":"股票信息","value":"182"},
{"name":"测试软件","value":"169"},
{"name":"发光材料","value":"149"},
{"name":"高考咨询","value":"142"},
{"name":"负极材料","value":"138"},
{"name":"粉末冶金材料","value":"132"},
{"name":"材料试验机","value":"118"},
{"name":"高分子复合材料","value":"115"},
{"name":"电子监控","value":"113"},
{"name":"点播系统","value":"106"},
{"name":"编程技术","value":"106"},
{"name":"高性能计算机","value":"101"},

]
@csrf_exempt
def getkeyword(request):
    i = random.randint(0,2)
    keywordlist = []
    for j in range(50):
            keywordlist.append(keyword_value[i*50+j])

    return JsonResponse(keywordlist, safe=False)
